# General Applied Math

## Overview

This section covers general applied math functions from NCL:

- [abs](https://www.ncl.ucar.edu/Document/Functions/Built-in/abs.shtml)
- [avg](https://www.ncl.ucar.edu/Document/Functions/Built-in/avg.shtml)
- [cumsum](https://www.ncl.ucar.edu/Document/Functions/Built-in/cumsum.shtml)
- [decimalPlaces](https://www.ncl.ucar.edu/Document/Functions/Contributed/decimalPlaces.shtml)
- [get_d2r](https://www.ncl.ucar.edu/Document/Functions/Contributed/get_d2r.shtml)
- [get_r2d](https://www.ncl.ucar.edu/Document/Functions/Contributed/get_r2d.shtml)
- [get_pi](https://www.ncl.ucar.edu/Document/Functions/Contributed/get_pi.shtml)
- [log](https://www.ncl.ucar.edu/Document/Functions/Built-in/log.shtml)
- [log10](https://www.ncl.ucar.edu/Document/Functions/Built-in/log10.shtml)
- [mod](https://www.ncl.ucar.edu/Document/Functions/Contributed/mod.shtml)
- [product](https://www.ncl.ucar.edu/Document/Functions/Contributed/mod.shtml)
- [sum](https://www.ncl.ucar.edu/Document/Functions/Built-in/sum.shtml)

## abs

NCL's `abs` function returns the absolute value of numeric data

### Grab and Go

In [8]:
# Input: Single Value
input_value = -3.14

abs_output = abs(input_value)
print(abs_output)

3.14


In [9]:
# Input: List
import numpy as np

input_values = [-10, -3.14, -123]

abs_output = np.abs(input_values)
print(abs_output)

[ 10.     3.14 123.  ]


## avg

NCL's `avg` function calculate the average of numeric values

### Grab and Go

In [10]:
# Input: Single Array
import numpy as np

input_value = [1, 2, 3]

avg_output = np.average(input_value)
print(avg_output)

2.0


In [11]:
# Input: List of a List - Flattened Array
import numpy as np

input_values = [[1, 2, 3], [4, 5, 6]]

avg_output = np.mean(input_values)
print(avg_output)

3.5


In [12]:
# Input: List of a List - Individual Arrays
import numpy as np

input_values = [[1, 2, 3], [4, 5, 6]]

avg_output = np.mean(input_values, axis=1)
print(avg_output)

[2. 5.]


## cumsum

NCL's `cumsum` function calculates the cumulative sum

### Grab and Go

In [13]:
import numpy as np

input_values = [1, 2, 3, 4, 5]

cumsum_output = np.cumsum(input_values, axis=0)
print(cumsum_output)

[ 1  3  6 10 15]


## decimalPlaces

NCL's `decimalPlaces` function truncates or rounds to the number of decimal places specified

### Grab and Go

In [14]:
# round: Single Value
input_value = 3.1415926

round_output = round(input_value, 3)
print(round_output)

3.142


In [15]:
# round: Array
import numpy as np

input_values = [-10.353535, 3.1415926, 123.4567]

round_output = np.round(input_values, 3)
print(round_output)

[-10.354   3.142 123.457]


In [16]:
# truncate: Single Value
import math

input_value = 3.1415926

decimal_values = str(input_value).split(".")
truncate_decimal = decimal_values[1][:3]
truncate_output = float(decimal_values[0] + "." + truncate_decimal)
print(truncate_output)

3.141


### Differences from NCL

NCL distinguishes between rounding a decimal value and truncating it as part of the `decimalPlaces` function

```
decimalPlaces(3.145, 2, True)  # True = rounds
>> 3.15
decimalPlaces(3.145, 2, False) # False = truncates
>> 3.14
```

Python includes multiple functions for rounding a value (`math.ceil`, `math.floor`, `round`), but does not typically handle truncating a value. To truncate a decimal value, the decimal needs to be converted to a string first.

The `round` function returns the value rounded to ndigits after the decimal point. 

```
round(3.141, 2)
>> 3.14
round(3.145, 2)
>> 3.15
```

<div class="admonition alert alert-info">
    <p class="admonition-title" style="font-weight:bold">Important Note</p>
    Python makes use of Banker's Rounding where a value is rounded to the nearest even integer, rather than automatically rounding up or rounding down
</div>

```
round(3.5)
>> 4
round(4.5)
>> 4
```

_See [Floating-Point Arithmetic: Issues and Limitations](https://docs.python.org/3/tutorial/floatingpoint.html#floating-point-arithmetic-issues-and-limitations) and [Built-in Numeric Types](https://docs.python.org/3/library/stdtypes.html#numeric-types-int-float-complex) for more information_

Use `math.ceil` to round up to the nearest integer
```
import math
math.ceil(3.14)
>> 4
```
Use `math.floor` to round down to the nearest integer
```
import math
math.floor(3.14)
>> 3
```

## get_d2r

NCL's `get_d2r` function returns a constant to convert degrees to radians

### Grab and Go

In [17]:
d2r = math.pi / 180
print(d2r)

0.017453292519943295


## get_r2d

NCL's `get_r2d` function returns a constant that converts radians to degrees

### Grab and Go

In [18]:
import math

r2d = 180 / math.pi
print(r2d)

57.29577951308232


## get_pi

NCL's `get_pi` function returns the value of pi

### Grab and Go

In [19]:
import math

pi = math.pi
print(pi)

3.141592653589793


In [1]:
import numpy as np

pi = np.pi
print(pi)

3.141592653589793


## log

NCL's `log` function calculates the natural log

### Grab and Go

In [20]:
# Input: Single Value
import math

input_value = 3.6

log_output = math.log(3.6)
print(log_output)

1.2809338454620642


In [2]:
# Input: List
import numpy as np

input_values = [3.5, 3.6, 3.7]

log_output = np.log(input_values)
print(log_output)

[1.25276297 1.28093385 1.30833282]


## log10

NCL's `log10` function calculate the log base 10

### Grab and Go

In [21]:
# Input: Single Value
import math

input_value = 3.4

log10_output = math.log10(input_value)
print(log10_output)

0.5314789170422551


In [4]:
# Input: List
import numpy as np

input_values = [3.3, 3.4, 3.5]

log10_output = np.log10(input_values)
print(log10_output)

[0.51851394 0.53147892 0.54406804]


## mod

NCL's `mod` function calculate the remainder of a division

### Grab and Go

In [22]:
mod_value = 17 % 3

print(mod_value)

2


In [23]:
# Numpy
import numpy as np

mod_values = np.mod([17, 4], [3, 3])
print(mod_values)

[2 1]


## product

NCL's `product` function calculate the product of input values

### Grab and Go

In [24]:
# Math
import math

input_values = [1, 3, 4, 6]
prod_math_output = math.prod(input_values)
print(prod_math_output)

72


In [25]:
# Numpy
import numpy as np

input_values = [1, 3, 4, 6]
prod_np_output = np.prod(input_values)
print(prod_np_output)

72


## sum

NCL's `sum` function calculate the sum of input values

### Grab and Go

In [26]:
# Built-In Python Sum
input_values = [1, 3, 4, 6]

sum_math_output = sum(input_values)
print(sum_math_output)

14


In [27]:
# Numpy
import numpy as np

input_values = [1, 3, 4, 6]
sum_np_output = np.sum(input_values)
print(sum_np_output)

14


---

## Python Resources
- [Built-in Python math](https://docs.python.org/3/library/math.html) functions documentation
- [Numpy math](https://numpy.org/doc/stable/reference/routines.math.html) function documentation
- [Python Floating-Point Arithmetic: Issues and Limitations](https://docs.python.org/3/tutorial/floatingpoint.html#floating-point-arithmetic-issues-and-limitations)
- [Python Built-In Types](https://docs.python.org/3/library/stdtypes.html#built-in-types)