# Trigonometric Functions

## Overview
The trigonometric functions for sine, cosine, and tangent (and associated inverse functions) are built-in functions in Python as well as part of a common Python package `numpy`

- [sin](https://www.ncl.ucar.edu/Document/Functions/Built-in/sin.shtml)
- [cos](https://www.ncl.ucar.edu/Document/Functions/Built-in/cos.shtml)
- [tan](https://www.ncl.ucar.edu/Document/Functions/Built-in/tan.shtml)
- [asin](https://www.ncl.ucar.edu/Document/Functions/Built-in/asin.shtml)
- [acos](https://www.ncl.ucar.edu/Document/Functions/Built-in/acos.shtml)
- [atan](https://www.ncl.ucar.edu/Document/Functions/Built-in/atan.shtml)

## Using the `math` and `cmath` module

The [`math`](https://docs.python.org/3/library/math.html#trigonometric-functions) and [`cmath`](https://docs.python.org/3/library/cmath.html#trigonometric-functions) modules are part of the Python Standard Library and require no additional downloading to use. Both math modules can be used to calculate the value of trigonometric functions in Python

Both math modules expect an input value in radians:
- Input: single numerical values (float, decimals, integers)
- Returns: single numerical value in radians as a float

The `math` function only works on real number inputs, while `cmath` contains equivalent functions for for complex and imaginary numbers

However, if you are working with lists or arrays we suggest using the `numpy` equivalents

## Recommended: Using `numpy`

[`numpy`](https://numpy.org/doc/stable/reference/routines.math.html) supports both real and complex values of individual numbers (floats, decimals, integers) as well as array-like values (arrays, lists, etc...)

`numpy` expects an input value in radians:
- Input: single or array-like numerical values (floats, integers, arrays, lists)
- Returns: single or array-like numerical values in radians as floats

## sin

`sin` calculates the sine of numeric values in radians

### Grab and Go

In [1]:
import math

input_value = 0.5  # in radians
math_sin_value = math.sin(input_value)
print(math_sin_value)

0.479425538604203


In [2]:
# Input: Single Value
import numpy as np

input_value = 0.5  # in radians
np_sin_value = np.sin(input_value)
print(np_sin_value)

0.479425538604203


In [3]:
# Input: Array
import numpy as np

input_values = np.array([0.5, 0.75, 1.0])  # in radians
np_sin_array_values = np.sin(input_values)
print(np_sin_array_values)

[0.47942554 0.68163876 0.84147098]


## cos

`cos` calculates the cosine of numeric values in radians

### Grab and Go

In [4]:
import math

input_value = 0.5  # in radians
math_cos_value = math.cos(input_value)
print(math_cos_value)

0.8775825618903728


In [5]:
# Input: Single Value
import numpy as np

input_value = 0.5  # in radians
np_cos_value = np.cos(input_value)
print(np_cos_value)

0.8775825618903728


In [6]:
# Input: Array
import numpy as np

input_values = np.array([0.5, 0.75, 1.0])  # in radians
np_cos_array_values = np.cos(input_values)
print(np_cos_array_values)

[0.87758256 0.73168887 0.54030231]


## tan

`tan` calculates the tangent of numeric values in radians

### Grab and Go

In [7]:
import math

input_value = 0.5  # in radians
math_tan_value = math.tan(input_value)
print(math_tan_value)

0.5463024898437905


In [8]:
# Input: Single Value
import numpy as np

input_value = 0.5  # in radians
np_tan_value = np.tan(input_value)
print(np_tan_value)

0.5463024898437905


In [9]:
# Input: Array
import numpy as np

input_values = np.array([0.5, 0.75, 1.0])  # in radians
np_tan_array_values = np.tan(input_values)
print(np_tan_array_values)

[0.54630249 0.93159646 1.55740772]


## asin

`asin` calculates the arcsine of numeric values in radians

### Grab and Go

In [10]:
import math

input_value = 0.5  # in radians
math_asin_value = math.asin(input_value)
print(math_asin_value)

0.5235987755982989


In [11]:
# Input: Single Value
import numpy as np

input_value = 0.5  # in radians
np_asin_value = np.arcsin(input_value)
print(np_asin_value)

0.5235987755982989


In [12]:
# Input: Array
import numpy as np

input_values = np.array([0.5, 0.75, 1.0])  # in radians
np_asin_array_values = np.arcsin(input_values)
print(np_asin_array_values)

[0.52359878 0.84806208 1.57079633]


## acos

`acos` calculates the arccosine of numeric values in radians

### Grab and Go

In [13]:
import math

input_value = 0.5  # in radians
math_acos_value = math.acos(input_value)
print(math_acos_value)

1.0471975511965979


In [14]:
# Input: Single Value
import numpy as np

input_value = 0.5  # in radians
np_acos_value = np.arccos(input_value)
print(np_acos_value)

1.0471975511965979


In [15]:
# Input: Array
import numpy as np

input_values = np.array([0.5, 0.75, 1.0])  # in radians
np_acos_array_values = np.arccos(input_values)
print(np_acos_array_values)

[1.04719755 0.72273425 0.        ]


## atan

`atan` calculates the arctangent of numeric values in radians

### Grab and Go

In [16]:
import math

input_value = 0.5  # in radians
math_atan_value = math.atan(input_value)
print(math_atan_value)

0.4636476090008061


In [17]:
# Input: Single Value
import numpy as np

input_value = 0.5  # in radians
np_atan_value = np.arctan(input_value)
print(np_atan_value)

0.4636476090008061


In [18]:
# Input: Array
import numpy as np

input_values = np.array([0.5, 0.75, 1.0])  # in radians
np_atan_array_values = np.arctan(input_value)
print(np_atan_array_values)

0.4636476090008061


## Differences from NCL

### Input and Return Types
While the math modules (`math` and `cmath`) only accept single numerical values—like NCL—`numpy` can accept and return either single numerical values or array-like values. 

Unlike NCL, `cmath` and `numpy` can also accept complex numbers as input values

## Python Resources

- The [`math` trig functions](https://docs.python.org/3/library/math.html#trigonometric-functions) module documentation
- The [`cmath` trig functions](https://docs.python.org/3/library/cmath.html#trigonometric-functions) module documentation
- The [`numpy` trig functions](https://numpy.org/doc/stable/reference/routines.math.html) documentation
- Converting between radians and degrees with `numpy`
  - [np.rad2deg](https://numpy.org/doc/stable/reference/generated/numpy.rad2deg.html): Convert angles from radians to degrees
  - [np.deg2rad](https://numpy.org/doc/stable/reference/generated/numpy.deg2rad.html): Convert angles from degrees to radians